using System;
using System.ComponentModel;

namespace Portfolio.Domain.Enum
{
    public enum Studio
    {
        [Description("20th Century Pictures")] TwentiethCenturyPictures,
        [Description("A24")] A24,
        [Description("ABC")] ABC,
        [Description("Amazon/Amazon Prime Video/Amazon Studios")] Amazon,
        [Description("Amblin Entertainment")] Amblin,
        [Description("Blue Sky Studios")] BlueSkyStudios,
        [Description("Castle Rock Entertainment")] CastleRockEntertainment,
        [Description("CBS")] CBS,
        [Description("Chesterfield Pictures")] ChesterfieldPictures,
        [Description("Columbia Pictures")] ColumbiaPictures,
        [Description("Dimension Films")] DimensionFilms,
        [Description("DreamWorks Animation")] DreamWorksAnimation,
        [Description("DreamWorks Pictures")] DreamWorksPictures,
        [Description("Eagle-Lion Films")] EagleLionFilms,
        [Description("Embassy Pictures")] EmbassyPictures,
        [Description("Film Booking Offices of America")] FilmBookingOfficesofAmerica,
        [Description("First National Pictures")] FirstNationalPictures,
        [Description("Focus Features")] FocusFeatures,
        [Description("Fox Film")] FoxFilm,
        [Description("Gaumont")] Gaumont,
        [Description("Grand National Pictures")] GrandNationalPictures,
        [Description("HBO Films")] HBOFilms,
        [Description("Illumination")] Illumination,
        [Description("Lantern Entertainment")] LanternEntertainment,
        [Description("Legendary Pictures")] LegendaryPictures,
        [Description("Lions Gate Entertainment")] LionsGateEntertainment,
        [Description("Lionsgate")] Lionsgate,
        [Description("Lippert Pictures")] LippertPictures,
        [Description("Lucasfilm")] Lucasfilm,
        [Description("Marvel Studios")] MarvelStudios,
        [Description("Metro Pictures")] MetroPictures,
        [Description("Metro-Goldwyn-Mayer")] MetroGoldwynMayer,
        [Description("Miramax Films")] MiramaxFilms,
        [Description("Monogram Pictures / Allied Artists Pictures")] MonogramPicturesAlliedArtistsPictures,
        [Description("Neon")] Neon,
        [Description("Netflix original films")] NetflixOriginalfilms,
        [Description("New Line Cinema")] NewLineCinema,
        [Description("Orion Pictures")] OrionPictures,
        [Description("Paramount British")] ParamountBritish,
        [Description("Pixar")] Pixar,
        [Description("Producers Releasing Corporation")] ProducersReleasingCorporation,
        [Description("Relativity Media")] RelativityMedia,
        [Description("Republic Pictures")] RepublicPictures,
        [Description("RKO Pictures")] RKOPictures,
        [Description("Roundhay Garden Scene")] RoundhayGardenScene,
        [Description("Saban Films")] SabanFilms,
        [Description("Searchlight Pictures")] SearchlightPictures,
        [Description("Sony Pictures Animation")] SonyPicturesAnimation,
        [Description("Sony Pictures Classics")] SonyPicturesClassics,
        [Description("Studio Ghibli")] StudioGhibli,
        [Description("StudioCanal")] StudioCanal,
        [Description("STX Entertainment")] STXEntertainment,
        [Description("Summit Entertainment")] SummitEntertainment,
        [Description("The Cannon Group")] TheCannonGroup,
        [Description("The Weinstein Company")] TheWeinsteinCompany,
        [Description("Tiffany Pictures")] TiffanyPictures,
        [Description("Touchstone Pictures")] TouchstonePictures,
        [Description("Triangle Films")] TriangleFilms,
        [Description("TriStar Pictures")] TriStarPictures,
        [Description("Troma")] Troma,
        [Description("United Artists")] UnitedArtists,
        [Description("Universal Pictures")] UniversalPictures,
        [Description("Vitagraph")] Vitagraph,
        [Description("Walt Disney Animation Studios")] WaltDisneyAnimationStudios,
        [Description("Walt Disney Pictures")] WaltDisneyPictures,
        [Description("Walt Disney Studios")] WaltDisneyStudios,
        [Description("Warner Animation Group")] WarnerAnimationGroup,
        [Description("World Film")] WorldFilm,
        [Description("Zazen Produções")] ZazenProduções,
    }
}
